
services:
  database:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    network_mode: host
    # ports:
    #   - '3306:3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
